/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package TERCERO;

import java.awt.Dimension;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author CAT
 */
public class Ventanatrabajo extends javax.swing.JFrame {

    /**
     * Creates new form Ventanausuario
     */
    public Ventanatrabajo() {
        initComponents();
        this.setMaximumSize(new Dimension(1180,842));
        this.setMinimumSize(new Dimension(1180,842));

        jPjava.setVisible(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPpropuesta2 = new javax.swing.JPanel();
        jLjava = new javax.swing.JLabel();
        jLjava1 = new javax.swing.JLabel();
        jLjava2 = new javax.swing.JLabel();
        jLjava3 = new javax.swing.JLabel();
        jLjava4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPjava = new javax.swing.JPanel();
        jLabel27 = new javax.swing.JLabel();
        jLabel58 = new javax.swing.JLabel();
        jLabel59 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel67 = new javax.swing.JLabel();
        jLabel68 = new javax.swing.JLabel();
        jLabel69 = new javax.swing.JLabel();
        jLabel70 = new javax.swing.JLabel();
        jLabel71 = new javax.swing.JLabel();
        jLabel72 = new javax.swing.JLabel();
        jLabel73 = new javax.swing.JLabel();
        jLabel74 = new javax.swing.JLabel();
        jLabel75 = new javax.swing.JLabel();
        jLabel76 = new javax.swing.JLabel();
        jLabel77 = new javax.swing.JLabel();
        jLabel80 = new javax.swing.JLabel();
        jLabel81 = new javax.swing.JLabel();
        jLabel82 = new javax.swing.JLabel();
        jLabel83 = new javax.swing.JLabel();
        jLabel84 = new javax.swing.JLabel();
        jLabel85 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 51, 255));
        jPanel1.setLayout(null);

        jPpropuesta2.setBackground(new java.awt.Color(255, 255, 255));
        jPpropuesta2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPpropuesta2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPpropuesta2MouseClicked(evt);
            }
        });
        jPpropuesta2.setLayout(null);

        jLjava.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLjava.setForeground(new java.awt.Color(0, 102, 255));
        jLjava.setText("JAVA FULL STACK/DEVELOPER");
        jLjava.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLjavaMouseClicked(evt);
            }
        });
        jPpropuesta2.add(jLjava);
        jLjava.setBounds(20, 10, 230, 40);

        jLjava1.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        jLjava1.setForeground(new java.awt.Color(0, 0, 0));
        jLjava1.setText("New Future Con");
        jLjava1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLjava1MouseClicked(evt);
            }
        });
        jPpropuesta2.add(jLjava1);
        jLjava1.setBounds(20, 50, 120, 20);

        jLjava2.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        jLjava2.setForeground(new java.awt.Color(0, 0, 0));
        jLjava2.setText("Guadalajara Jalisco");
        jLjava2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLjava2MouseClicked(evt);
            }
        });
        jPpropuesta2.add(jLjava2);
        jLjava2.setBounds(20, 70, 130, 20);

        jLjava3.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jLjava3.setForeground(new java.awt.Color(102, 102, 102));
        jLjava3.setText("Salario mensual de 50,000 a 60,000 . Ubicado: Guadalajara Jalisco - Contrato permanente");
        jLjava3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLjava3MouseClicked(evt);
            }
        });
        jPpropuesta2.add(jLjava3);
        jLjava3.setBounds(20, 110, 490, 20);

        jLjava4.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jLjava4.setForeground(new java.awt.Color(102, 102, 102));
        jLjava4.setText("Vigencia de la oferta: 13 de septiembre de 2019...");
        jLjava4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLjava4MouseClicked(evt);
            }
        });
        jPpropuesta2.add(jLjava4);
        jLjava4.setBounds(20, 130, 480, 20);

        jPanel1.add(jPpropuesta2);
        jPpropuesta2.setBounds(0, 80, 530, 210);

        jLabel1.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel1.setText("VACANTES DE TRABAJO");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(130, 30, 260, 40);

        jButton1.setBackground(new java.awt.Color(153, 153, 153));
        jButton1.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("POSTULARME");
        jButton1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(340, 300, 190, 40);

        jPjava.setBackground(new java.awt.Color(204, 204, 204));
        jPjava.setLayout(null);

        jLabel27.setFont(new java.awt.Font("Calibri", 0, 17)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(0, 0, 0));
        jLabel27.setText("-SQL/SqlServer");
        jPjava.add(jLabel27);
        jLabel27.setBounds(370, 420, 170, 30);

        jLabel58.setFont(new java.awt.Font("Calibri", 0, 17)); // NOI18N
        jLabel58.setForeground(new java.awt.Color(0, 0, 0));
        jLabel58.setText("-HTML, CSS");
        jPjava.add(jLabel58);
        jLabel58.setBounds(30, 420, 300, 30);

        jLabel59.setFont(new java.awt.Font("Calibri", 0, 17)); // NOI18N
        jLabel59.setForeground(new java.awt.Color(0, 0, 0));
        jLabel59.setText("-Angular");
        jPjava.add(jLabel59);
        jLabel59.setBounds(370, 390, 170, 30);

        jLabel9.setFont(new java.awt.Font("Calibri", 1, 20)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("JAVA DEVELOPER");
        jPjava.add(jLabel9);
        jLabel9.setBounds(30, 20, 160, 40);

        jLabel30.setFont(new java.awt.Font("Calibri", 0, 17)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(0, 0, 0));
        jLabel30.setText("Guadalajara, Jalisco");
        jPjava.add(jLabel30);
        jLabel30.setBounds(50, 60, 160, 30);

        jLabel67.setFont(new java.awt.Font("Calibri", 0, 17)); // NOI18N
        jLabel67.setForeground(new java.awt.Color(0, 0, 0));
        jLabel67.setText("Salario de 50,000 a 60,000 mensuales");
        jPjava.add(jLabel67);
        jLabel67.setBounds(50, 90, 270, 30);

        jLabel68.setFont(new java.awt.Font("Calibri", 1, 17)); // NOI18N
        jLabel68.setForeground(new java.awt.Color(0, 0, 0));
        jLabel68.setText("Descripción de la vacante");
        jPjava.add(jLabel68);
        jLabel68.setBounds(30, 120, 190, 30);

        jLabel69.setFont(new java.awt.Font("Calibri", 0, 17)); // NOI18N
        jLabel69.setForeground(new java.awt.Color(0, 0, 0));
        jLabel69.setText("Contratación: Tiempo completo");
        jPjava.add(jLabel69);
        jLabel69.setBounds(30, 150, 230, 30);

        jLabel70.setFont(new java.awt.Font("Calibri", 0, 17)); // NOI18N
        jLabel70.setForeground(new java.awt.Color(0, 0, 0));
        jLabel70.setText("Categoria: Tecnologías de la información / Sistemas, Desarrollador  de Software");
        jPjava.add(jLabel70);
        jLabel70.setBounds(30, 180, 560, 30);

        jLabel71.setFont(new java.awt.Font("Calibri", 0, 17)); // NOI18N
        jLabel71.setForeground(new java.awt.Color(0, 0, 0));
        jLabel71.setText("New Future Con es una empresa dedicada al software conformada de un equipo");
        jPjava.add(jLabel71);
        jLabel71.setBounds(30, 210, 560, 30);

        jLabel72.setFont(new java.awt.Font("Calibri", 0, 17)); // NOI18N
        jLabel72.setForeground(new java.awt.Color(0, 0, 0));
        jLabel72.setText("dedicado profesionalmente con más de 50 años de experiencia.");
        jPjava.add(jLabel72);
        jLabel72.setBounds(30, 240, 560, 30);

        jLabel73.setFont(new java.awt.Font("Calibri", 0, 17)); // NOI18N
        jLabel73.setForeground(new java.awt.Color(0, 0, 0));
        jLabel73.setText("Estamos totalmente orgullosos de que gracias a nuestro servicio de calidad,");
        jPjava.add(jLabel73);
        jLabel73.setBounds(30, 270, 560, 30);

        jLabel74.setFont(new java.awt.Font("Calibri", 0, 17)); // NOI18N
        jLabel74.setForeground(new java.awt.Color(0, 0, 0));
        jLabel74.setText("nuestros clientes confían en nosotros como socios comerciales. Las Soluciones ");
        jPjava.add(jLabel74);
        jLabel74.setBounds(30, 300, 560, 30);

        jLabel75.setFont(new java.awt.Font("Calibri", 0, 17)); // NOI18N
        jLabel75.setForeground(new java.awt.Color(0, 0, 0));
        jLabel75.setText("innovadoreas en RH, Ingeniería y TI nos han ayudado a un crecimiento con el 100%.");
        jPjava.add(jLabel75);
        jLabel75.setBounds(30, 330, 580, 30);

        jLabel76.setFont(new java.awt.Font("Calibri", 1, 17)); // NOI18N
        jLabel76.setForeground(new java.awt.Color(0, 0, 0));
        jLabel76.setText("Habilidades:");
        jPjava.add(jLabel76);
        jLabel76.setBounds(30, 360, 90, 30);

        jLabel77.setFont(new java.awt.Font("Calibri", 0, 17)); // NOI18N
        jLabel77.setForeground(new java.awt.Color(0, 0, 0));
        jLabel77.setText("-Java Standar Edition, java EE, java (v.6 o 8)");
        jPjava.add(jLabel77);
        jLabel77.setBounds(30, 390, 300, 30);

        jLabel80.setFont(new java.awt.Font("Calibri", 1, 17)); // NOI18N
        jLabel80.setForeground(new java.awt.Color(0, 0, 0));
        jLabel80.setText("Zona de trabajo:");
        jPjava.add(jLabel80);
        jLabel80.setBounds(30, 450, 120, 30);

        jLabel81.setFont(new java.awt.Font("Calibri", 0, 17)); // NOI18N
        jLabel81.setForeground(new java.awt.Color(0, 0, 0));
        jLabel81.setText("Zona centro Guadalajara, Jalisco av juares #1322");
        jPjava.add(jLabel81);
        jLabel81.setBounds(150, 450, 450, 30);

        jLabel82.setFont(new java.awt.Font("Calibri", 0, 17)); // NOI18N
        jLabel82.setForeground(new java.awt.Color(0, 0, 0));
        jLabel82.setText("-Lunes a Viernes");
        jPjava.add(jLabel82);
        jLabel82.setBounds(30, 480, 130, 30);

        jLabel83.setFont(new java.awt.Font("Calibri", 0, 17)); // NOI18N
        jLabel83.setForeground(new java.awt.Color(0, 0, 0));
        jLabel83.setText("-9:00 am a 18:00 pm");
        jPjava.add(jLabel83);
        jLabel83.setBounds(30, 510, 150, 30);

        jLabel84.setFont(new java.awt.Font("Calibri", 1, 17)); // NOI18N
        jLabel84.setForeground(new java.awt.Color(0, 0, 0));
        jLabel84.setText("Telefono:");
        jPjava.add(jLabel84);
        jLabel84.setBounds(30, 540, 70, 30);

        jLabel85.setFont(new java.awt.Font("Calibri", 0, 17)); // NOI18N
        jLabel85.setForeground(new java.awt.Color(0, 0, 0));
        jLabel85.setText("3389769009");
        jPjava.add(jLabel85);
        jLabel85.setBounds(110, 540, 150, 30);

        jPanel1.add(jPjava);
        jPjava.setBounds(540, 80, 640, 650);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLjavaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLjavaMouseClicked
        if(jPpropuesta2.isEnabled() || jLjava.isEnabled() || jLjava1.isEnabled() || jLjava2.isEnabled() || jLjava3.isEnabled() || jLjava4.isEnabled()){
          
            jPjava.setVisible(true);
           
        }
    }//GEN-LAST:event_jLjavaMouseClicked

    private void jLjava1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLjava1MouseClicked
         if(jPpropuesta2.isEnabled() || jLjava.isEnabled() || jLjava1.isEnabled() || jLjava2.isEnabled() || jLjava3.isEnabled() || jLjava4.isEnabled()){
            
            jPjava.setVisible(true);
            
        }
    }//GEN-LAST:event_jLjava1MouseClicked

    private void jLjava2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLjava2MouseClicked
         if(jPpropuesta2.isEnabled() || jLjava.isEnabled() || jLjava1.isEnabled() || jLjava2.isEnabled() || jLjava3.isEnabled() || jLjava4.isEnabled()){
            
            jPjava.setVisible(true);
          
        }
    }//GEN-LAST:event_jLjava2MouseClicked

    private void jLjava3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLjava3MouseClicked
         if(jPpropuesta2.isEnabled() || jLjava.isEnabled() || jLjava1.isEnabled() || jLjava2.isEnabled() || jLjava3.isEnabled() || jLjava4.isEnabled()){
           
            jPjava.setVisible(true);
          
        }
    }//GEN-LAST:event_jLjava3MouseClicked

    private void jLjava4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLjava4MouseClicked
         if(jPpropuesta2.isEnabled() || jLjava.isEnabled() || jLjava1.isEnabled() || jLjava2.isEnabled() || jLjava3.isEnabled() || jLjava4.isEnabled()){
           
            jPjava.setVisible(true);
         
        }
    }//GEN-LAST:event_jLjava4MouseClicked

    private void jPpropuesta2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPpropuesta2MouseClicked
         if(jPpropuesta2.isEnabled() || jLjava.isEnabled() || jLjava1.isEnabled() || jLjava2.isEnabled() || jLjava3.isEnabled() || jLjava4.isEnabled()){
          
            jPjava.setVisible(true);
     
        }
    }//GEN-LAST:event_jPpropuesta2MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if(jPjava.isVisible()==true){//ninguna validacion solamente sino da click en el trabajo entonces te mandara un mensaje que lo selecciones
            Cventana cv=new Cventana();
            cv.setVisible(true);
            cv.setLocationRelativeTo(null);
            dispose();
        }else{
            JOptionPane.showMessageDialog(this, "Favor de seleccionar su oferta de trabajo","Aviso",JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventanatrabajo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventanatrabajo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventanatrabajo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventanatrabajo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Ventanatrabajo tra=new Ventanatrabajo();
                tra.setVisible(true);
                tra.setLocationRelativeTo(null);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel67;
    private javax.swing.JLabel jLabel68;
    private javax.swing.JLabel jLabel69;
    private javax.swing.JLabel jLabel70;
    private javax.swing.JLabel jLabel71;
    private javax.swing.JLabel jLabel72;
    private javax.swing.JLabel jLabel73;
    private javax.swing.JLabel jLabel74;
    private javax.swing.JLabel jLabel75;
    private javax.swing.JLabel jLabel76;
    private javax.swing.JLabel jLabel77;
    private javax.swing.JLabel jLabel80;
    private javax.swing.JLabel jLabel81;
    private javax.swing.JLabel jLabel82;
    private javax.swing.JLabel jLabel83;
    private javax.swing.JLabel jLabel84;
    private javax.swing.JLabel jLabel85;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLjava;
    private javax.swing.JLabel jLjava1;
    private javax.swing.JLabel jLjava2;
    private javax.swing.JLabel jLjava3;
    private javax.swing.JLabel jLjava4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPjava;
    private javax.swing.JPanel jPpropuesta2;
    // End of variables declaration//GEN-END:variables
}
